services:
  vite:
    build:
      context: ../../apps/Portfolio.React
    container_name: vite
    working_dir: /app
    volumes:
      - ../../apps/Portfolio.React:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      bash -c "npm install && npm run dev -- --host 0.0.0.0"
