FROM mcr.microsoft.com/dotnet/sdk:8.0

# Install Azure Functions Core Tools
RUN wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y azure-functions-core-tools-4 && \
    rm packages-microsoft-prod.deb && \
    apt-get clean

WORKDIR /app

EXPOSE 7071
